runtime: php55
api_version: 1

handlers:
- url: /staticdata
  static_dir: staticdata
  
- url: /crCount.php
  script: crCount.php
  
  - url: /crShowLog.php
  script: crShowLog.php

- url: /staticdata/crCount.js
  script: /staticdata/crCount.js

- url: /.*
  script: crCountMain.php
